name: BrainTumor
channels:
  - defaults
dependencies:
  - aiodns=3.5.0=py311haa95532_0
  - aiohappyeyeballs=2.6.1=py311haa95532_0
  - aiohttp=3.12.15=py311h02ab6af_0
  - aiosignal=1.4.0=py311haa95532_0
  - altair=5.5.0=py311haa95532_0
  - aom=3.6.0=hd77b12b_0
  - arrow-cpp=21.0.0=h0399227_0
  - attrs=24.3.0=py311haa95532_0
  - aws-c-auth=0.9.0=h02ab6af_2
  - aws-c-cal=0.9.2=h02ab6af_1
  - aws-c-common=0.12.4=h02ab6af_0
  - aws-c-compression=0.3.1=h02ab6af_2
  - aws-c-event-stream=0.5.6=h02ab6af_0
  - aws-c-http=0.10.4=h02ab6af_0
  - aws-c-io=0.21.4=h02ab6af_0
  - aws-c-mqtt=0.13.3=h02ab6af_0
  - aws-c-s3=0.8.7=h02ab6af_0
  - aws-c-sdkutils=0.2.4=h02ab6af_1
  - aws-checksums=0.2.7=h02ab6af_1
  - aws-crt-cpp=0.34.0=h885b0b7_0
  - aws-sdk-cpp=1.11.638=hf0af688_0
  - blas=1.0=mkl
  - blinker=1.9.0=py311haa95532_0
  - bottleneck=1.4.2=py311h57dcf0c_0
  - brotlicffi=1.0.9.2=py311h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.9.9=haa95532_0
  - cachetools=5.5.1=py311haa95532_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2025.10.5=py311haa95532_0
  - cffi=2.0.0=py311h02ab6af_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.2.1=py311haa95532_0
  - colorama=0.4.6=py311haa95532_0
  - contourpy=1.3.1=py311h214f63a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - datasets=2.12.0=py311haa95532_0
  - dav1d=1.2.1=h2bbff1b_0
  - dill=0.3.6=py311haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - filelock=3.17.0=py311haa95532_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py311h02ab6af_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - frozenlist=1.5.0=py311h827c3e9_0
  - fsspec=2025.7.0=py311hbc747e5_0
  - gflags=2.2.2=hd77b12b_1
  - giflib=5.2.2=h7edc060_0
  - gitdb=4.0.12=py311haa95532_0
  - gitpython=3.1.43=py311haa95532_0
  - glog=0.5.0=hd77b12b_1
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py311h827c3e9_0
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=10.2.0=he2f9f60_1
  - hf-xet=1.1.8=py311h79d111c_0
  - huggingface_hub=0.34.4=py311haa95532_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.7=py311haa95532_0
  - imageio=2.37.0=py311haa95532_0
  - importlib-metadata=8.5.0=py311haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.6=py311haa95532_0
  - joblib=1.5.2=py311haa95532_0
  - jpeg=9f=ha349fce_0
  - jsonschema=4.25.0=py311haa95532_0
  - jsonschema-specifications=2023.7.1=py311haa95532_0
  - kiwisolver=1.4.8=py311h5da7b33_0
  - lazy_loader=0.4=py311haa95532_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libavif=1.1.1=h827c3e9_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libcurl=8.15.0=h2300eb9_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.2=h405b238_0
  - libgrpc=1.71.0=hf4237ab_0
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h4a159e6_2
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.15.0=ha2884a9_4
  - libtiff=4.7.0=h404307b_0
  - libtorch=2.5.1=cpu_mkl_h9002858_104
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.8=h866ff63_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py311h827c3e9_0
  - matplotlib=3.10.6=py311haa95532_0
  - matplotlib-base=3.10.6=py311h43afe63_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h827c3e9_2
  - mkl_fft=1.3.11=py311h827c3e9_0
  - mkl_random=1.2.8=py311hea22821_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py311haa95532_0
  - multidict=6.1.0=py311h827c3e9_0
  - multiprocess=0.70.14=py311haa95532_0
  - narwhals=2.7.0=py311haa95532_0
  - networkx=3.5=py311haa95532_0
  - numexpr=2.11.0=py311hdb065b2_0
  - numpy-base=1.26.4=py311hd01c5d8_0
  - openjpeg=2.5.2=h9b5d1b5_1
  - openssl=3.0.18=h543e019_0
  - opentelemetry-api=1.37.0=py311haa95532_0
  - orc=2.2.0=hf43e1a1_0
  - packaging=25.0=py311haa95532_0
  - pandas=2.3.3=py311ha5e6156_0
  - pcre2=10.42=h0ff8eda_1
  - pillow=11.3.0=py311hb328d1f_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - propcache=0.3.1=py311h827c3e9_0
  - protobuf=5.29.3=py311h5da7b33_0
  - pyarrow=21.0.0=py311ha5e6156_0
  - pycares=4.10.0=py311he29e43d_0
  - pycparser=2.23=py311haa95532_0
  - pyparsing=3.2.0=py311haa95532_0
  - pyqt=6.7.1=py311h378bd72_2
  - pyqt6-sip=13.9.1=py311h02ab6af_2
  - pysocks=1.7.1=py311haa95532_0
  - python=3.11.13=h981015d_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py311h827c3e9_0
  - pytorch=2.5.1=cpu_mkl_py311h0452e45_104
  - pytz=2025.2=py311haa95532_0
  - pyyaml=6.0.2=py311h827c3e9_0
  - qtbase=6.7.3=hd088775_4
  - qtdeclarative=6.7.3=h885b0b7_1
  - qtsvg=6.7.3=h9d4b640_1
  - qttools=6.7.3=hcb596f7_1
  - qtwebchannel=6.7.3=h885b0b7_1
  - qtwebsockets=6.7.3=h885b0b7_1
  - re2=2024.07.02=h214f63a_0
  - referencing=0.30.2=py311haa95532_0
  - regex=2025.9.1=py311h02ab6af_0
  - requests=2.32.5=py311haa95532_0
  - responses=0.13.3=pyhd3eb1b0_0
  - rpds-py=0.22.3=py311h636fa0f_0
  - safetensors=0.5.3=py311h8eb67e2_0
  - scikit-image=0.25.2=py311h094160a_0
  - scikit-learn=1.7.2=py311h9296b3f_0
  - scipy=1.12.0=py311h9f229c6_0
  - seaborn=0.13.2=py311haa95532_3
  - setuptools=72.1.0=py311haa95532_0
  - sip=6.10.0=py311h5da7b33_0
  - six=1.17.0=py311haa95532_0
  - sleef=3.5.1=h8cc25b3_2
  - smmap=5.0.2=py311haa95532_0
  - snappy=1.2.1=hcdb6601_0
  - sqlite=3.50.2=hda9a48d_1
  - streamlit=1.50.0=py311haa95532_0
  - sympy=1.14.0=py311haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tenacity=9.0.0=py311haa95532_0
  - threadpoolctl=3.5.0=py311h746a85d_0
  - tifffile=2025.10.4=py311haa95532_0
  - tk=8.6.15=hf199647_0
  - tokenizers=0.21.0=py311hbb1481a_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchvision=0.20.1=cpu_py311h99a9fa7_2
  - tornado=6.5.1=py311h827c3e9_0
  - tqdm=4.67.1=py311h746a85d_0
  - transformers=4.51.3=py311haa95532_0
  - typing-extensions=4.15.0=py311haa95532_0
  - typing_extensions=4.15.0=py311haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py311haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchdog=6.0.0=py311haa95532_0
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_0
  - winloop=0.2.2=py311h913537a_0
  - xxhash=0.8.0=h2bbff1b_3
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yarl=1.18.0=py311h827c3e9_0
  - zipp=3.21.0=py311haa95532_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - grad-cam==1.5.5
      - mahotas==1.4.18
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - segmentation-models-pytorch==0.5.0
      - timm==1.0.20
      - ttach==0.0.3
prefix: C:\Users\Nobody\anaconda3\envs\BrainTumor
